# Generated by Django 5.0.6 on 2024-06-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('invoice_no', models.IntegerField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Customer Name')),
                ('fe', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='First Entry')),
                ('fe_quantity', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Quantity')),
                ('fe_unit_price', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Unit Price')),
                ('fe_totals', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Entry Totals')),
                ('se', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Second Entry')),
                ('se_quantity', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Quantity')),
                ('se_unit_price', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Unit Price')),
                ('se_totals', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Entry Totals')),
                ('te', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Third Entry')),
                ('te_quantity', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Quantity')),
                ('te_unit_price', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Unit Price')),
                ('te_totals', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Entry Totals')),
                ('fte', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Fourth Entry')),
                ('fte_quantity', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Quantity')),
                ('fte_unit_price', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Unit Price')),
                ('fte_totals', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Entry Totals')),
                ('ffe', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Fifth Entry')),
                ('ffe_quantity', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Quantity')),
                ('ffe_unit_price', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Unit Price')),
                ('ffe_totals', models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Entry Totals')),
                ('contact', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('balance', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('inv_selection', models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('Invoice', 'Invoice'), ('Debit Note', 'Debit Note'), ('Credit Note', 'Credit Note')], default='', max_length=120, null=True)),
            ],
        ),
    ]
