# Generated by Django 5.0.6 on 2024-06-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='fe_totals',
            field=models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Totals'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ffe_totals',
            field=models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Totals'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fte_totals',
            field=models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Totals'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='se_totals',
            field=models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Totals'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='te_totals',
            field=models.IntegerField(blank=True, default=0, max_length=120, null=True, verbose_name='Totals'),
        ),
    ]
